---
title: "Joins"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Data Wrangling Refresher

```{r}
penguins %>%
  filter(island == "Dream" | island == "Biscoe") %>% #filter(island %in% c("Dream", "Biscoe"))
  select(-c(sex, year)) %>%
  mutate(body_mass_kg = body_mass_g / 1000) %>%
  rename(location = island)
```

```{r}
penguins %>%
  filter(species == "Adelie") %>%
  drop_na(flipper_length_mm, sex) %>%
  group_by(sex) %>%
  summarise(mean = mean(flipper_length_mm), 
            sd = sd(flipper_length_mm), 
            sample_size = n())
```

```{r}
penguins %>%
  count(species, island, sex, name = "sample_size")
```

## {datapasta}

Addins -\> paste as tribble / paste as data frame

```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )
animals

sites <- data.frame(
  stringsAsFactors = FALSE,
  location = c("beach", "lagoon", "bluff", "oaks"),
  full_site_name = c("Goleta Beach","UCSB Lagoon","Ellwood Mesa",
                     "Fremont Campground"),
  jurisdiction = c("SB City", "UCSB", "SB City", "USFS")
)
sites
```

## Joins

Full Join

```{r}
full_join_example <- full_join(animals, sites)
full_join_example
```

Left Join

```{r}
left_join_example <- left_join(animals, sites)
left_join_example
```

Right Join

```{r}
right_join_example <- right_join(animals, sites)
right_join_example
```

Inner Join

```{r}
inner_join_example <- inner_join(animals, sites)
inner_join_example
```

Filtering Join

-   semi_join(): returns all rows from x with a match in y

-   anti_join(): returns all rows from x without a match in y

```{r}
semi_join_example <- semi_join(animals, sites)
semi_join_example

anti_join_example <- anti_join(animals, sites)
anti_join_example
```
